{{- if .Values.llm.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-llm-credentials
  labels:
    {{- include "nemo-guardrails.labels" . | nindent 4 }}
stringData:
  api-key: {{ .Values.llm.apiKey | quote }}
{{- end }}
{{- if and .Values.llamaGuard.enabled .Values.llamaGuard.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-llama-guard-credentials
  labels:
    {{- include "nemo-guardrails.labels" . | nindent 4 }}
stringData:
  api-key: {{ .Values.llamaGuard.apiKey | quote }}
{{- end }}
